---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - sysctl_install
        - sysctl_configure
        - sysctl_run
  tags:
    - sysctl_install
    - sysctl_configure
    - sysctl_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - sysctl_install
  tags:
    - sysctl_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - sysctl_configure
  tags:
    - sysctl_configure

- name: Flush handlers after run.
  ansible.builtin.meta: flush_handlers
